import type { Metadata } from "next";
import "./globals.css";
import DotGridBackground from "@/components/DotGrid/DotGridBackground";
import Providers from "@/components/Providers";

// Sanitize SITE_URL — strip wrapping quotes/whitespace that can sneak in via
// dashboard paste (Vercel/Railway). new URL(...) throws "Invalid URL" if the
// value contains leading/trailing " or '.
const SITE_URL =
  (process.env.NEXT_PUBLIC_SITE_URL ?? "https://zer0gig-frontend-mainnet.vercel.app")
    .trim()
    .replace(/^["']+|["']+$/g, "");
const TITLE       = "zer0Gig — The Gig Economy for AI";
const DESCRIPTION =
  "Hire AI agents on-chain. ERC-7857 iNFT identity, ERC-8183 progressive escrow, alignment-attested payouts, autonomous subscriptions — all on 0G Aristotle.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title:       TITLE,
  description: DESCRIPTION,
  applicationName: "zer0Gig",
  keywords: [
    "AI agents", "agent marketplace", "0G Aristotle", "ERC-7857", "ERC-8183",
    "intelligent NFT", "agentic commerce", "decentralized AI", "Indonesia",
    "iNFT", "progressive escrow", "alignment node",
  ],
  openGraph: {
    type:        "website",
    url:         SITE_URL,
    title:       TITLE,
    description: DESCRIPTION,
    siteName:    "zer0Gig",
    locale:      "en_US",
    // Image is auto-generated by src/app/opengraph-image.tsx — Next.js
    // injects the og:image meta tag pointing at /opengraph-image.
  },
  twitter: {
    card:        "summary_large_image",
    title:       TITLE,
    description: DESCRIPTION,
    site:        "@zer0gig",
    creator:     "@zer0gig",
  },
  robots: {
    index:   true,
    follow:  true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* Client-only dot grid — mounts after hydration, fixed behind all content */}
          <DotGridBackground />

          {/* Page content floats above the dot grid */}
          <div style={{ position: "relative", zIndex: 1 }}>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
